apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rosinabot
  name: rosinabot
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosinabot
  strategy: {}
  template:
    metadata:
      labels:
        app: rosinabot
    spec:
      containers:
      - image: ghcr.io/filariow/gardenia/bot:14c557e@sha256:ff7a611665a70305748a3a31c74efa0fede7ba3a217d3427eb4df0ac5276ffb2
        name: bot
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: rosinabot-token
              key: token
        - name: "SKEDULER_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key: skeduler-address
              name: bot-cm
        - name: "PROMETHEUS_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key: prometheus-address
              name: bot-cm
        - name: "VALVED_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key: valved-address
              name: bot-cm
        - name: "ROSINA_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key: rosina-address
              name: bot-cm
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - "ALL"
