apiVersion: v1
kind: ConfigMap
metadata:
  name: skeduler-cm
  namespace: system
data:
  address: ":12000"
  application: "rosina"
  run-image: "ghcr.io/filariow/gardenia/rosinacli:14c557e@sha256:ac8bd174c15dfc4147c09375a0b3f522980087a632f4af0f48fc5057df9fe628"
  rosina-address: "rpi-valve.service.com:12000"
