apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: skeduler
  labels:
    app: skeduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skeduler
  template:
    metadata:
      labels:
        app: skeduler
    spec:
      serviceAccountName: skeduler
      containers:
        - name: skeduler
          image: ghcr.io/filariow/gardenia/skeduler:215cda9@sha256:2ace2f42572ff12f5c508e71a0acb66bdac1bf1e0c1063d9db50650a113155b8  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 12000
          env:
            - name: "ADDRESS"
              valueFrom:
                configMapKeyRef:
                  key: address
                  name: skeduler-cm
            - name: "APPLICATION"
              valueFrom:
                configMapKeyRef:
                  key: application
                  name: skeduler-cm
            - name: "RUN_IMAGE"
              valueFrom:
                configMapKeyRef:
                  key: run-image
                  name: skeduler-cm
            - name: "ROSINA_ADDRESS"
              valueFrom:
                configMapKeyRef:
                  key: rosina-address
                  name: skeduler-cm
