apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skeduler-role-binding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skeduler
subjects:
  - kind: ServiceAccount
    name: skeduler
