apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: system
  name: skeduler
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get","watch","list","create","update","delete"]
