apiVersion: v1
kind: Service
metadata:
  namespace: system
  name: skeduler
spec:
  selector:
    app: skeduler
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
