# https://grafana.github.io/grafana-operator/docs/installation/kustomize/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

# this will automatically pull the latest release when `kustomize build` is executed
resources:
- https://github.com/grafana/grafana-operator/releases/latest/download/kustomize-cluster_scoped.yaml

patches:
  - patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
        name: grafanas.grafana.integreatly.org 
