apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: system
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  ruleSelector:
    matchLabels:
      app: "rosina"
  alerting:
    alertmanagers:
    # TODO: use kustomize replacements
    - namespace: rosina
      name: rosina
      port: web
  resources:
    requests:
      memory: 400Mi
  retention: 90d
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
stringData:
  prometheus-additional.yaml: |
    - job_name: "flowmeter"
      static_configs:
      - targets: ["rpi-valve.service.com:12113"]
    - job_name: "valved"
      static_configs:
      - targets: ["rpi-valve.service.com:2112"]
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: system
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-rosina
  namespace: system
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-rosina
  namespace: system
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: rosina
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rosina
  name: rosina-flow-rules
  namespace: system
spec:
  groups:
  - name: ./rosina.rules
    rules:
    - alert: water-flowing
      expr: "avg(flow_last_minute) > 1"
      for: "10s"
      labels:
        job: flowmeter
        namespace: rosina # use replacements
