apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns
spec:
  project: default
  source:
    repoURL: 'https://github.com/filariow/gardenia-ops'
    path: components/dns
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
