apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: op-prometheus
spec:
  project: default
  source:
    repoURL: 'https://github.com/filariow/gardenia-ops'
    path: operators/prometheus
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
